### PR TITLE
s390x: mask e_ident

### PR DESCRIPTION
**Pull request by rphillips**
* Support 0x03 (Linux) and 0x00 (System V)

### CODE REVIEW

**Comment by rphillips** [comment]
@moul can you review this PR as well before cutting a new release?

**Comment by rphillips** [comment]
should fix https://github.com/kubernetes/ingress-nginx/issues/1108 as well

**Comment by rphillips** [comment]
travis is failing due to the publish script not having the right credentials...

**Comment by moul** [comment]
Well done 👍

**Comment by rphillips** [comment]
@moul can you release a 2.9.1-1 version? or something similar?

**Comment by moul** [comment]
@rphillips -> https://github.com/multiarch/qemu-user-static/releases/tag/v2.9.1-1

**Comment by rphillips** [comment]
perfect. thank you

**Pull request merged**
