### PR TITLE
fix s390 again

### PR DESCRIPTION
**Pull request by MHBauer**
fix in https://github.com/multiarch/qemu-user-static/pull/31 was undone in https://github.com/multiarch/qemu-user-static/commit/6a9c52b5456fc9325f5de4602d250607890af956 

needs an image respin after it goes in.

### CODE REVIEW

**Comment by aledbf** [comment]
@MHBauer thank you. I was checking if someone reported the issue

**Comment by MHBauer** [comment]
As context, this is blocking our releases https://github.com/kubernetes-incubator/service-catalog/issues/2093 which use the automated build image `multiarch/qemu-user-static:register`.

**Comment by carolynvs** [comment]
Thanks for the quick fix! 💖

**Comment by MHBauer** [comment]
Thank you. I appreciate your attention.

**Pull request merged**
